language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: L15idyAoO9DYJYYQexbdGh82jpFNZ3LCy9SDFolmy7n0QQNtg0C2lQaQe5GnEEJLGmjXLznktgDo3nEt1LIyszJo1BtJkNy8lp0pXUwgum58aav9G+UEH0rFbpChN5iKUlEuD0r/7pE9vBwmQiNMBZydkTiHLuqLH2Iw4WGfopIDnDZEsHtVs8kLz1YYehZHa3mX87TndoEgADhnkuid8fOqV0tLe+pkWReuvQsfWNcOGworPl4dLZ2Gi07FHygptA/FYWDs2qa9jCRuJ3x+8RF4JwdHHW9UIfJFg3bIqDVIPZgOB0AdDv5XnSMLHh82qAHkvcigcJw93Z26PUOQdovidNXXY03xCWqhG6vSpw7c3ypt5ofPQvw1fjB8vYpkuHgWeDdxdrcZTT8T5xxaKfy15wNUTXRUqnTUqWpwEdS9fyDqRNGWSC8kT4zbmJftx3feIHpzZPRtz119EgvkO97/BI1iXScRq4DIhxarZmRgJmPMxfGavyVaOZlP1x/E2LiZ9gwWe4vllXUDfXgt5O8eBSjlWgPHWKn9ZZYyWn03lXP971LaUb3yVNh7aTzrGYYLsJYcH3VrYsLGH6+knHUq3uXr88nBxMlSh0X5nSP8cJiyogAIDFdIa7prd3SvA9rMSTj+Kvq0ZydDC4CExDXlg/CEX4KpJmrSKqlLRCc=
  app: enigmatic-fortress-65227
  on:
    repo: melodyplan/node-restaurants-app-mongoose
